#167806860 User can edit comment
andela/mazus-ah-backend pull request #60
Opened 2019-08-12 18:15 UTC by VictorMaria

#### What does this PR do?
User can edit their own comment on article

#### Description of Task to be completed?
Has /api/v1/comments/${commentId} working

![Edit comment (1)](https://user-images.githubusercontent.com/41482184/62887589-74ae3100-bd35-11e9-864c-561ffe9f4936.jpeg)

#### How should this be manually tested?
1. Fetch this branch on the terminal using 
git fetch origin ft-edit-comment-167806860
2. Install dependencies using npm install
3. Start the server with npm run server
4. On Postman, sign in as a verified user by making a POST request to /api/v1/auth/signin and use the token received for the request in the next step.
5. Call /api/v1/comments/${commentId} 

#### Note
You can only edit your own existing comment. Also ensure you enter a valid input in the body of the request

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#167806860](https://www.pivotaltracker.com/story/show/167806860)

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-08-12 at 6 24 30 PM" src="https://user-images.githubusercontent.com/41482184/62887628-87c10100-bd35-11e9-8581-7d8acbbf5459.png">

2019-08-13 05:54 UTC, ocranbillions approved these changes
Good job bro. Kindly document your feature and push again.

2019-08-13 05:54 UTC, ocranbillions commented on controllers/CommentController.js
> +        return errorResponse(res, 403, 'You are not allowed to edit another user\'s comment');
Good job checking if the user is the owner of the comment.

2019-08-13 05:54 UTC, ocranbillions commented on __tests__/editComment.test.js
> +        expect(res.body.errors).to.eql('You are not allowed to edit another user\'s comment');
Nice!

2019-08-13 20:21 UTC, tolulope-od approved these changes
LGTM, please check your flowchart, it seems to point that the request will give a server error once it's made

2019-08-14 03:50 UTC, VictorMaria commented on __tests__/editComment.test.js
> +        expect(res.body.errors).to.eql('You are not allowed to edit another user\'s comment');
Thank you

2019-08-14 03:51 UTC, VictorMaria commented
> LGTM, please check your flowchart, it seems to point that the request will give a server error once it's made

Yeah, That part was tricky for me. I will look into it. Thank you.

2019-08-14 09:37 UTC, Tunji17 approved these changes
LGTM

2019-08-14 10:02 UTC, VictorMaria commented
> LGTM

Thank you

2019-08-14 12:29 UTC, profmcdan commented
Why are you returning a 403 for invalid token? @VictorMaria

2019-08-14 12:31 UTC, profmcdan requested changes
You need to return the right status code for an invalid token, from the flowchart. 
Also, ensure that your code implementation follows the same approach.

2019-08-14 12:46 UTC, VictorMaria commented
> Why are you returning a 403 for invalid token? @VictorMaria

It has been corrected. My feature strictly follows the flowchart

2019-08-14 14:11 UTC, profmcdan approved these changes

2019-08-14 14:12 UTC, profmcdan requested changes
From the diagram that I can see on your PR, I can still see a 403 being returned. What exactly did you fix?

2019-08-14 14:23 UTC, VictorMaria commented
@profmcdan I have uploaded the correct flowchart again

2019-08-14 16:55 UTC, OdunayoOkebunmi commented on docs/comments/editComment.json
> +                "example": "nice one"
Good job. But this returns the "body" as a string, not an object

2019-08-15 08:20 UTC, profmcdan approved these changes

2019-08-15 08:21 UTC, merged