#167783502 Fetch All Tags
andela/mazus-ah-backend pull request #65
Opened 2019-08-14 16:06 UTC by ocranbillions

### What does this PR do?
- Fetches all tags

#### Description of Task to be completed?
- Create /articles/tags endpoint
- Fetch tagList for each article
- Concatenate all tagLists from artcles into one tagList
- Remove duplicate
- Return TagsArray

#### How should this be manually tested?
- Open the review-app on this PR and make a get request to /articles/tags

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [#167783502](https://www.pivotaltracker.com/story/show/167783502)

#### Screenshots (if appropriate)
<img width="466" alt="Screenshot 2019-08-14 at 5 05 31 PM" src="https://user-images.githubusercontent.com/20531075/63036851-c5e52e80-beb5-11e9-8b53-4278c6804718.png">

2019-08-15 07:42 UTC, Tunji17 commented on controllers/TagsController.js
> +      const allTags = [...new Set(tagsArray)];
nice work here

2019-08-15 07:42 UTC, Tunji17 approved these changes
LGTM

2019-08-15 09:24 UTC, profmcdan commented on controllers/TagsController.js
> +      let tagsArray = [];
```js
let tagSet = new Set();
```

2019-08-15 09:31 UTC, profmcdan requested changes
Implement the requested feedback

2019-08-15 11:13 UTC, ocranbillions commented
> Implement the requested feedback

Feedback implemented

2019-08-16 08:59 UTC, mekzy-o approved these changes
Nice Job Samuel. LGTM

2019-08-16 09:15 UTC, profmcdan approved these changes

2019-08-16 09:15 UTC, merged