#167165082 Implements Get  Comment Edit History
andela/mazus-ah-backend pull request #66
Opened 2019-08-14 17:11 UTC by OdunayoOkebunmi

### What does this PR do?
- user can see previous versions of comments
- adds tests to cover edge cases
- add swagger documentation
#### Description of Task to be completed?
As a user, I should be able to see the previous versions of comments made on an article after previous edits.
![API Flowchart (4)](https://user-images.githubusercontent.com/28678648/63040596-a9e58b00-bebd-11e9-83cf-4ccd6e3a7902.png)

#### How should this be manually tested?
After cloning this repo, `cd` into it and do the following:

```bash
# fetch this branch
$ git fetch origin  ft-comment-edit-history-167165082

# install dependencies
$ npm install

# run unit tests
$ npm test

# start the development server
$ npm run server
```
Using postman, run /api/v1/comments/{id} 

#### What are the relevant pivotal tracker stories?
[#1167165082](https://www.pivotaltracker.com/story/show/167165082)

#### Screenshots (if appropriate)
<img width="1133" alt="Screenshot 2019-08-14 at 18 04 19" src="https://user-images.githubusercontent.com/28678648/63041103-f2ea0f00-bebe-11e9-85c1-324df5a0b19f.png">

2019-08-15 08:38 UTC, PelumiAlesh commented on controllers/CommentController.js
> +        return errorResponse(res, 403, 'You are not allowed to edit another user\'s comment');
@OdunayoOkebunmi  Is this error message correct? Is this not meant to be 'You are not allowed to view another user\'s comment history'

2019-08-15 10:12 UTC, profmcdan requested changes
Your present implementation is not particularly correct, this is meant to be an admin feature, so its the admin or anyone with the required privileges that should be able to pull edit history on a comment.

Try to attend to this.

2019-08-16 06:37 UTC, tolulope-od commented on controllers/CommentController.js
> +        return errorResponse(res, 404, { message: 'Comment does not have edit history' });
Wouldn't it be better to just return the empty array here?

2019-08-16 16:13 UTC, profmcdan approved these changes

2019-08-16 16:14 UTC, merged